"use client";

import { useEffect, useState } from "react";
import api from "@/lib/api";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default function ProfitLossPage() {
  const [data, setData] = useState<any>(null);
  const [from, setFrom] = useState(new Date(new Date().getFullYear(), 0, 1).toISOString().split('T')[0]);
  const [to, setTo] = useState(new Date().toISOString().split('T')[0]);
  const [loading, setLoading] = useState(true);

  const fetchReport = () => {
    setLoading(true);
    api.get(`/reports/profit-loss?from=${from}&to=${to}`)
      .then(res => setData(res.data))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchReport();
  }, [from, to]);

  const renderRows = (items: any[]) => (
    <div className="space-y-2">
      {items?.map((item, idx) => (
        <div key={idx} className="flex justify-between text-sm py-1.5 px-2 hover:bg-slate-50 transition-colors">
          <span className="text-slate-600">[{item.code}] {item.name}</span>
          <span className="font-mono">৳{item.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
        </div>
      ))}
    </div>
  );

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <Card className="shadow-xl">
        <div className="p-8 border-b bg-emerald-50 flex justify-between items-center rounded-t-xl">
          <div>
            <h1 className="text-2xl font-black text-emerald-900 tracking-tight uppercase">Profit & Loss</h1>
            <p className="text-emerald-700 text-xs font-bold tracking-widest uppercase">Income Statement</p>
          </div>
          <div className="flex gap-4">
             <div>
               <label className="text-[10px] font-black uppercase text-slate-500 mb-0.5 block">From</label>
               <Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="h-8 text-xs bg-white" />
             </div>
             <div>
                <label className="text-[10px] font-black uppercase text-slate-500 mb-0.5 block">To</label>
                <Input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="h-8 text-xs bg-white" />
             </div>
          </div>
        </div>

        <CardContent className="p-8 pt-10 space-y-12 min-h-[400px]">
          {loading ? (
             <div className="flex items-center justify-center py-20 text-emerald-600 font-black animate-bounce">CALCULATING REVENUE...</div>
          ) : (
            <>
              <div>
                <h3 className="text-lg font-black text-slate-900 uppercase tracking-tighter mb-4 flex items-center gap-2">
                   <div className="w-1.5 h-6 bg-emerald-500 rounded-full"></div> REVENUE
                </h3>
                {renderRows(data?.income)}
                <div className="mt-4 flex justify-between font-black text-emerald-700 border-t pt-2 h-10 px-2 items-center bg-emerald-50 rounded">
                   <span>GROSS REVENUE</span>
                   <span className="text-lg">৳{data?.total_income?.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
                </div>
              </div>

              <div>
                <h3 className="text-lg font-black text-slate-900 uppercase tracking-tighter mb-4 flex items-center gap-2">
                   <div className="w-1.5 h-6 bg-red-500 rounded-full"></div> OPERATING EXPENSES
                </h3>
                {renderRows(data?.expenses)}
                <div className="mt-4 flex justify-between font-black text-red-700 border-t pt-2 h-10 px-2 items-center bg-red-50 rounded">
                   <span>TOTAL EXPENSES</span>
                   <span className="text-lg">৳{data?.total_expense?.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
                </div>
              </div>

              <div className={`mt-12 p-6 rounded-2xl border-4 ${data?.net_profit >= 0 ? 'bg-emerald-600 border-emerald-400 text-white' : 'bg-red-600 border-red-400 text-white shadow-red-100 shadow-xl'}`}>
                 <div className="flex justify-between items-center">
                    <div>
                      <span className="text-xs uppercase font-black opacity-80 tracking-widest">Fiscal Performance</span>
                      <h2 className="text-2xl font-black italic">NET {data?.net_profit >= 0 ? 'PROFIT' : 'LOSS'}</h2>
                    </div>
                    <div className="text-4xl font-black font-mono tracking-tighter">
                      ৳{data?.net_profit?.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                    </div>
                 </div>
              </div>
            </>
          )}
        </CardContent>
      </Card>
      <div className="text-center text-[10px] text-slate-400 font-bold uppercase tracking-widest opacity-50">Draft generated by SolarEdge Financial Core. Audit verified: {new Date().toLocaleDateString()}</div>
    </div>
  );
}
